config/routes.rb
Rails.application.routes.draw do
	root 'cards#index'
  resources :cards
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
	self.inheritance_column = :_type_disabled

	def self.getir(params)
  	if params.class == String
	  	search(params)
	  elsif params.class == ActionController::Parameters
	  	params.delete("commit")
			params.delete("controller")
			params.delete("action")
	  	filter(params)
	  else
	  	self.all
	  end
	end

	def self.search(params)
		query = [
			# "associatedCardRefs", 
			# "assets", 
			"region", 
			# "regionRef", 
			# "attack", 
			"cost", 
			# "health", 
			"description", 
			# "descriptionRaw", 
			# "levelupDescription", 
			# "levelupDescriptionRaw", 
			# "flavorText", 
			# "artistName", 
			"name", 
			# "cardCode", 
			"keywords", 
			# "keywordRefs", 
			"spellSpeed", 
			# "spellSpeedRef", 
			"rarity", 
			# "rarityRef", 
			"subtype", 
			# "subtypes", 
			"supertype", 
			"type", 
			# "collectible"
		]

	 	list = params.split(' ') unless params.nil?

		result = []
		unless list.empty?
			query.each do |column|
				list.each do |word|
	    		result = result | self.where("collectible = ? AND \"#{column}\" LIKE ?","t", "%#{word}%")
	    	end
			end
		else
			result = self.all
		end
		result
	end

	def self.filter(params)
		result = []

		if params.include? :type
			if (params.include? :regions) && (params.include? :costs)
				params[:regions].each do |region|
					params[:costs].each do |cost|
						result |= self.where("collectible = ? AND region = ? AND cost = ? AND type = ?","t", region, cost, params[:type])
					end
				end
			elsif params.include? :regions
				params[:regions].each do |region|
					result |= self.where("collectible = ? AND region = ? AND type = ?","t", region, params[:type])
				end
			elsif params.include? :costs
				params[:costs].each do |cost|
					result |= self.where("collectible = ? AND cost = ? AND type = ?","t", cost, params[:type])
				end
			else
				result = self.where("collectible = ? AND type = ?","t", params[:type])
			end
		else
			if (params.include? :regions) && (params.include? :costs)
				params[:regions].each do |region|
					params[:costs].each do |cost|
						result |= self.where("collectible = ? AND region = ? AND cost = ?","t", region, cost)
					end
				end
			elsif params.include? :regions
				params[:regions].each do |region|
					result |= self.where("collectible = ? AND region = ?","t", region)
				end
			elsif params.include? :costs
				params[:costs].each do |cost|
					result |= self.where("collectible = ? AND cost = ?","t", cost)
				end
			else
				result = self.all
			end
		end	

		result
	end

	def show
		puts <<-TEXT
associatedCardRefs    : #{self.associatedCardRefs}
assets                : #{self.assets}
region                : #{self.region}
regionRef             : #{self.regionRef}
attack                : #{self.attack}
cost                  : #{self.cost}
health                : #{self.health}
description           : #{self.description}
descriptionRaw        : #{self.descriptionRaw}
levelupDescription    : #{self.levelupDescription}
levelupDescriptionRaw : #{self.levelupDescriptionRaw}
flavorText            : #{self.flavorText}
artistName            : #{self.artistName}
name                  : #{self.name}
cardCode              : #{self.cardCode}
keywords              : #{self.keywords}
keywordRefs           : #{self.keywordRefs}
spellSpeed            : #{self.spellSpeed}
spellSpeedRef         : #{self.spellSpeedRef}
rarity                : #{self.rarity}
rarityRef             : #{self.rarityRef}
subtype               : #{self.subtypes}
supertype             : #{self.supertype}
type                  : #{self.type}
collectible           : #{self.collectible}
		TEXT
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
	def index
		puts "OUTPUT** #{params}"

		if params[:commit] == "Search"
			@cards = Card.getir(params[:search])
		elsif params[:commit] == "Filter"
			@cards = Card.getir(params)
		else
			@cards = Card.where("collectible = ?", "t")
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_cards.html.erb
<% unless cards.nil? %>
	<% cards.each do |card| %>
		<div class="col-3" style="height:auto;width:auto;">
			<%= image_tag "#{card.gameAbsolutePath.insert(4, "s")}", size: 'height:auto;width:auto;', class: 'card-img-top', alt: "#{card.cardCode}"%>
		</div>
	<% end %>
<% else %>
	<p class="text-light">Eslesen kart yok</p>
<% end %>

app/views/cards/_filter_form.html.erb
<%= form_tag cards_path, remote: true, method: 'get' do %>
  <div class="form-group">
		<h5>REGIONS</h5>
	  <div class="btn-group btn-group-toggle" data-toggle="buttons">
	  	<label class="btn btn-info">
				<%= check_box_tag "regions[]", "Piltover & Zaun" %> Piltover & Zaun
		  </label>

		  <label class="btn btn-info">
				<%= check_box_tag "regions[]", "Shadow Isles" %> Shadow Isles
		  </label>

		  <label class="btn btn-info">
				<%= check_box_tag "regions[]", "Noxus" %> Noxus
		  </label>

		  <label class="btn btn-info">
				<%= check_box_tag "regions[]", "Demacia" %> Demacia
		  </label>

		  <label class="btn btn-info">
				<%= check_box_tag "regions[]", "Ionia" %> Ionia
		  </label>

		  <label class="btn btn-info">
				<%= check_box_tag "regions[]", "Bilgewater" %> Bilgewater
		  </label>

		  <label class="btn btn-info">
				<%= check_box_tag "regions[]", "Freljord" %> Freljord
		  </label>
	  </div>
	</div>

  <div class="form-group">
  	<h5>TYPES</h5>
	  <div class="btn-group btn-group-toggle" data-toggle="buttons">
	  	<label class="btn btn-info">
				<%= radio_button_tag "type", "Unit" %> Unit
		  </label>

		  <label class="btn btn-info">
				<%= radio_button_tag "type", "Spell" %> Spell
		  </label>
	  </div>
  </div>

  <div class="form-group">
  	<h5>COSTS</h5>
	  <div class="btn-group btn-group-toggle" data-toggle="buttons">
	  	<% costs = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]  %>
	  	<% costs.delete(11) %>
	  	<% costs.each do |cost| %>
		  	<label class="btn btn-info">
	        <%= check_box_tag "costs[]", cost %> <%= cost %>
			  </label>
      <% end %>

	  </div>
  </div>
	
	<div class="d-flex justify-content-end">
		<%= submit_tag "Filter", class: 'btn btn-outline-info'%>
	</div>

<% end %>

app/views/cards/_search_form.html.erb
<%= form_tag cards_path, remote: true, method: 'get' do %>
	<div class="input-group">
		<%= text_field_tag :search, params[:search], class: 'form-control',  placeholder: "Search", "aria-label": "Search" %>
		<div class="input-group-append">
			<%= submit_tag "Search", class: 'btn btn-outline-info' %>
		</div>
	</div>
<% end %>

app/views/cards/index.html.erb
<div class="container">
	<div class="pt-3 text-light">
		<div class="row d-flex justify-content-center">
			<%= render 'search_form' %>
		</div>
		<div class="row d-flex justify-content-center">
			<%= render 'filter_form' %>
		</div>
	</div>
	<div class="row pt-3" id="cards">
		<% @cards.each do |card| %>
			<div class="col-3" style="height:auto;width:auto;">
				<%= image_tag "#{card.gameAbsolutePath.insert(4, "s")}", size: 'height:auto;width:auto;', class: 'card-img-top', alt: "#{card.cardCode}"%>
			</div>
		<% end %>
	</div>
</div>

app/views/cards/index.js.erb
$("#cards").children().fadeOut("300", function() {
	$(this).remove();
});

$("#cards").fadeIn("300", function() {
	$(this).append("<%= j render 'cards', cards: @cards %>");
});

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LorDeckBuilder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-dark">
    <%= yield %>
  </body>
</html>